---
- name: restart node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted
    daemon_reload: yes

- name: restart promtail
  ansible.builtin.systemd:
    name: promtail
    state: restarted
    daemon_reload: yes
    
- name: restart journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted