---
- name: Deploy HA Storage Cluster
  hosts: storage_cluster
  become: true
  roles:
    - role: storage
      tags: storage
    - role: keepalived
      tags: keepalived

- name: Deploy Database Cluster
  hosts: db_cluster
  become: true
  roles:
    - role: postgresql
      tags: postgres
    - role: keepalived
      tags: keepalived

- name: Deploy Gitea HAProxy Load Balancers
  hosts: gitea_proxies
  become: yes
  roles:
    - role: haproxy
      tags: haproxy
    - role: keepalived
      tags: keepalived

- name: Deploy Application Layer (Gitea)
  hosts: gitea_servers
  become: true
  roles:
    - role: gitea
      tags: gitea

- name: Deploy Monitoring Agents
  hosts: all
  become: true
  roles:
    - role: monitoring_agents
      tags: monitoring

- name: Deploy Centralized Monitoring and Logging
  hosts: monitoring_server
  become: true
  roles:
    - role: monitoring_server
      tags: monitoring

- name: Deploy Backup Server
  hosts: backup
  become: true
  roles:
    - role: restic_server
      tags: backup_srv

- name: Deploy Backup Agents
  hosts: db_cluster:storage_cluster
  become: true
  roles:
    - role: restic_agent
      tags: backup_agents
