[all:vars]
ansible_connection=docker
ansible_user=root
ansible_remote_tmp=/tmp/.ansible
ansible_python_interpreter=/usr/bin/python3

[db_cluster]
db-node-01 ansible_host=db-node-01 ip_addr=172.20.0.21 keepalived_priority=110 is_master=true node_id=1
db-node-02 ansible_host=db-node-02 ip_addr=172.20.0.22 keepalived_priority=100 is_master=false node_id=2
[gitea_servers]
gitea-node-01 ansible_host=gitea-node-01 ip_addr=172.20.0.20
gitea-node-02 ansible_host=gitea-node-02 ip_addr=172.20.0.21

[storage_cluster]
storage-01 ansible_host=storage-01 ip_addr=172.20.0.41 keepalived_priority=110
storage-02 ansible_host=storage-02 ip_addr=172.20.0.42 keepalived_priority=100


[backup]
backup-srv ansible_host=backup-srv ip_addr=172.20.0.60


[infrastructure:children]
db_cluster
gitea_servers
storage_cluster
backup
monitoring_server
proxies

[proxies]
gitea-proxy proxy_type=gitea
db-proxy proxy_type=db
nfs-proxy proxy_type=nfs

[monitoring_server]
monitor-node-01 ansible_host=monitor-node-01 ip_addr=172.20.0.50